name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: ESLint
      run: yarn lint
    - name: Build
      run: yarn build
    - name: Create artifacts
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: |
          output
